### ISSUE TITLE
Use javax @Convert annotation to convert attributes automatically

### ISSUE THREAD

**Issue by kazablock** [jzheng2017/resultset-mapper#20]
`**Is` your feature request related to a problem? Please describe.**
Hi @jzheng2017 ,
Thanks for the awesome library it is really simple and easy to use.

Use case:
use @Convert annotation to convert between one attribute type to another just like javax.persistence.Convert
Example
//one of the columns in entity
```
@Column(name = "UPDATE_DATETIME")
    @Convert(converter = LocalDateTimeConverter.class)
    private LocalDateTime updateDatetime;
```

//Convertor class
```
@Converter(autoApply = true)
public class LocalDateTimeConverter implements AttributeConverter<LocalDateTime, Timestamp> {

    @Override
    public Timestamp convertToDatabaseColumn(LocalDateTime localDateTime) {
        return localDateTime == null ? null : Timestamp.valueOf(localDateTime);
    }

    @Override
    public LocalDateTime convertToEntityAttribute(Timestamp timestamp) {
        return timestamp == null ? null : timestamp.toLocalDateTime();
    }

}
```

It will be really useful if we can automatically map the convertor class if the @convert annotation is present.

Thanks in advance!

**Comment by jzheng2017** [comment]
Hey @kazablock thanks for using this library. This seems like an interesting feature. I'll get back to you soon, when I have more time to think about it.

**Comment by jzheng2017** [comment]
Hi @kazablock , I've added support for attribute converting. See the commit that is linked to this issue. It is a bit different from the example you showed. Your example has a two way mapping from database object to entity attribute and the other way around. This would not make sense in the context of this library as the mapping is only one way. Therefore the attribute converting is also one way.

I will update the documentation and make a new release soon.

**Comment by jzheng2017** [comment]
Documentation has been updated and [release ](https://github.com/jzheng2017/resultset-mapper/releases/tag/1.5.0)has been made.

**Comment by kazablock** [comment]
Thanks a lot 😀

**Comment by jzheng2017** [comment]
> Thanks a lot 😀

No problem, let me know if it works alright for you.
