### ISSUE TITLE
ResultSetMapper not tolerant to field 'null' values.

### ISSUE THREAD

**Issue by taras-beschastniy** [jzheng2017/resultset-mapper#38]
**Describe the bug**
Null values for fields cannot be set because of NPE.

**To Reproduce**
1. Describe any sql query which return null values in it's response.
2. Describe entity which has nullable type for those values.
3. NPE occures when mapper.map(rs, class);

**Expected behavior**
Null value should be set to such field.

**Additional context**
ResultSetMapper:172
We should just check for null and return null in this case (skipping futher logic).

**Comment by jzheng2017** [comment]
Hey! Sorry for the late response, I just noticed this issue. I will investigate this issue shortly. Thanks for creating an issue.

**Comment by jzheng2017** [comment]
A little late but I have fixed it now. Issue will be closed.
